### ISSUE TITLE
Can't Remap Tab

### ISSUE THREAD

**Issue by alexanderbianchi** [chomosuke/term-edit.nvim#55]
In order to remap tab you would need to use a string "tab" 

<img width="847" alt="image" src="https://github.com/chomosuke/term-edit.nvim/assets/75697973/9064eecd-bba3-4033-82c8-45fb668394c3">

Which the Lua LSP is not a fan of.  Resulting in...

<img width="1116" alt="image" src="https://github.com/chomosuke/term-edit.nvim/assets/75697973/623f51db-fab3-4a62-ac7b-e2dc5b92def3">

Tab is used in another plugin of mine, so I need to set it to false.

**Comment by chomosuke** [comment]
You need to replace `"tab"` with `["<tab>"]`.

**Comment by alexanderbianchi** [comment]
<img width="606" alt="image" src="https://github.com/chomosuke/term-edit.nvim/assets/75697973/9ecf54f5-b6b2-4e58-affb-a5a421c517bf">

Fixes the linting errors, but doesn't remap tab

"tab" = false does remap tab, after you continue through the error.

**Comment by chomosuke** [comment]
That's because this plugin doesn't remap tab at all. A fact I just remembered.

Maybe your syntax error prevents some other code of yours being ran.

**Comment by alloc33** [comment]
same here - I use tab to switch to command mode... ditching this plugin  🤷‍♂️

**Comment by chomosuke** [comment]
@alloc33 If this plugin actually interact with tab in some way, I would love some reproducible config.

**Comment by alloc33** [comment]
> [@alloc33](https://github.com/alloc33) If this plugin actually interact with tab in some way, I would love some reproducible config.

I use custom keyboard and I remapped `:` to `tab`:

```lua
    vim.api.nvim_set_keymap("n", "<tab>", ':', { noremap = true, silent = false, desc = "Enter command mode" })
    vim.api.nvim_set_keymap("v", "<tab>", ':', { noremap = true, silent = false, desc = "Enter command mode" })
 ```

So not sure how to make it work properly. Not going back to `:` because of this plugin... But it nice and I would like to use it.

**Comment by zSuperx** [comment]
This behavior is mistaken for a `<Tab>` conflict because when you press`<Tab>` and `<C-i>`, most terminals send the same keycode.

I would like to figure out a root-level fix for this--for example, I spent my entire evening diving down the Kitty Keyboard Protocol rabbit hole to no avail. Nothing I do seems to allow Neovim to distinguish the 2 keys. So for the time being I'm forking this project literally just to remove this line:

https://github.com/chomosuke/term-edit.nvim/blob/29c4584c2cef44a3fdcc55860957d081b892a569/lua/term-edit/map/insert_map.lua#L8

I would suggest the author to add a feature to modify this keybind, or at the very least pick something less troublesome than `<C-i>`, but it's really not _this_ project's problem to solve, but Neovim (or even terminal emulators) itself.

Anyways, hope this helps.
